[package]
name = "ontour"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
log = "0.4.16"
rmp-serde = "1.0.0"
thiserror = "1.0.30"
wapc = "0.10.1"
wasmtime-provider = "0.0.7"
